apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-backend-ingress
  namespace: gym
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: gym-backend-service
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gym-backend-service
                port:
                  number: 8080