apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-backend-config
  namespace: gym
data:
  SPRING_PROFILES_ACTIVE: "default"

  LOG_LEVEL_SECURITY: "DEBUG"
  LOG_LEVEL: "DEBUG"

  # CORS for local
  ALLOWED_ORIGINS: "http://gym.local,http://192.168.1.100,*"