apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml

# FluxCD connfiguration to pull image from GitHub Container Registry
images:
  - name: gym-backend
    newName: ghcr.io/fillwiel/gym-scheduler
    newTag: main