apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-backend
  template:
    metadata:
      labels:
        app: gym-backend
    spec:
      containers:
        - name: gym-backend
          image: gym-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: MONGODB_URI
            - name: AUTH_COOKIE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: AUTH_COOKIE_TOKEN
            - name: DEFAULT_MEMBER_ID
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: DEFAULT_MEMBER_ID
            - name: DAYS_RANGE
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: DAYS_RANGE
            - name: SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: SECURITY_USER_NAME
            - name: SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gym-backend-secrets
                  key: SECURITY_USER_PASSWORD