apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-backend
  namespace: gym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-backend
  template:
    metadata:
      labels:
        app: gym-backend
    spec:
      containers:
        - name: gym-backend
          image: gym-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5000
              name: management
          envFrom:
            - configMapRef:
                name: gymscheduler-config
            - secretRef:
                name: gymscheduler-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10