apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-backend-config
  namespace: gym
data:
  # Spring configuration
  SPRING_PROFILES_ACTIVE: "prod"
  GYMSCHEDULER_BE_PORT: "8080"
  MANAGEMENT_PORT: "5000"
  # Logging levels
  LOG_LEVEL_SECURITY: "INFO"
  LOG_LEVEL: "INFO"
  # App configuration
  DAYS_RANGE: "5"
  # CORS (patched per environment)
  ALLOWED_ORIGINS: "http://localhost"
  CORS_ALLOW_CREDENTIALS: "false"
  # MongoDB URI (PLACEHOLDER - be patched by overlays) - currently in secrets
#  MONGODB_URI: "PLACEHOLDER"
#  ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:30002,https://localhost:30002/,http://gym-frontend"
#  CORS_ALLOW_CREDENTIALS: "false"